export const apiEndpoints = Object.freeze({
  auth: Object.freeze({
    login: '/auth/login',
    signup: '/auth/register',
    refresh: '/auth/refresh',
    firebaseToken: '/auth/firebase-token',
  }),
  users: Object.freeze({
    me: '/users/me',
  }),
  profile: Object.freeze({
    me: '/profile/me',
    update: '/profile',
  }),
  dashboard: Object.freeze({
    overview: '/dashboard/overview',
  }),
  settings: Object.freeze({
    account: '/settings/account',
    notifications: '/settings/notifications',
    privacy: '/settings/privacy',
    password: '/settings/password',
  }),
  media: Object.freeze({
    reserve: '/media',
    ready: (mediaId) => `/media/${mediaId}/ready`,
    attach: (mediaId) => `/media/${mediaId}/attach`,
    mine: '/media',
    byParent: (parentType, parentId) => `/media/for/${parentType}/${parentId}`,
    remove: (mediaId) => `/media/${mediaId}`,
  }),
  feed: Object.freeze({
    list: '/feed',
    trendingTopics: '/feed/topics/trending',
  }),
  pitchReels: Object.freeze({
    list: '/pitch-reels',
    create: '/pitch-reels',
    draftMe: '/pitch-reels/draft/me',
    byId: (pitchReelId) => `/pitch-reels/${pitchReelId}`,
  }),
  livePitches: Object.freeze({
    list: '/live-pitches',
    byId: (livePitchId) => `/live-pitches/${livePitchId}`,
    vote: (livePitchId) => `/live-pitches/${livePitchId}/vote`,
    fund: (livePitchId) => `/live-pitches/${livePitchId}/fund`,
    chat: (livePitchId) => `/live-pitches/${livePitchId}/chat`,
    chatByMessage: (livePitchId, messageId) => `/live-pitches/${livePitchId}/chat/${messageId}`,
    watcherTouch: (livePitchId) => `/live-pitches/${livePitchId}/watcher-touch`,
    leaderboard: (livePitchId) => `/live-pitches/${livePitchId}/leaderboard`,
  }),
  fundme: Object.freeze({
    list: '/fundme',
    byId: (campaignId) => `/fundme/${campaignId}`,
    myCampaigns: '/fundme/me',
    supported: '/fundme/supported',
    following: '/fundme/following',
    contribute: (campaignId) => `/fundme/${campaignId}/contributions`,
    activity: '/fundme/activity',
  }),
  bizbucks: Object.freeze({
    wallet: '/bizbucks/wallet',
    transactions: '/bizbucks/transactions',
    purchase: '/bizbucks/purchases',
    transfer: '/bizbucks/transfers',
  }),
  credtrack: Object.freeze({
    overview: '/credtrack/overview',
    actionPlan: '/credtrack/action-plan',
    actionById: (actionId) => `/credtrack/action-plan/${actionId}`,
  }),
  groups: Object.freeze({
    list: '/groups',
    create: '/groups',
    byId: (groupId) => `/groups/${groupId}`,
    bySlug: (slug) => `/groups/slug/${slug}`,
    posts: (groupId) => `/groups/${groupId}/posts`,
    events: (groupId) => `/groups/${groupId}/events`,
    join: (groupId) => `/groups/${groupId}/join`,
  }),
  events: Object.freeze({
    list: '/events',
    create: '/events',
    byId: (eventId) => `/events/${eventId}`,
    bySlug: (slug) => `/events/slug/${slug}`,
    rsvp: (eventId) => `/events/${eventId}/rsvp`,
  }),
  courses: Object.freeze({
    list: '/courses',
    byId: (courseId) => `/courses/${courseId}`,
    progress: (courseId) => `/courses/${courseId}/progress`,
    notes: (courseId) => `/courses/${courseId}/notes`,
  }),
  marketplace: Object.freeze({
    list: '/marketplace',
    create: '/marketplace',
    byId: (listingId) => `/marketplace/${listingId}`,
    purchase: (listingId) => `/marketplace/${listingId}/purchase`,
    messageSeller: (listingId) => `/marketplace/${listingId}/messages`,
  }),
  messages: Object.freeze({
    conversations: '/messages/conversations',
    byId: (conversationId) => `/messages/conversations/${conversationId}`,
    send: (conversationId) => `/messages/conversations/${conversationId}/messages`,
  }),
  analytics: Object.freeze({
    overview: '/analytics/overview',
    content: '/analytics/content',
    export: '/analytics/export',
  }),
  bizquest: Object.freeze({
    challenges: '/bizquest/challenges',
    byId: (challengeId) => `/bizquest/challenges/${challengeId}`,
    join: (challengeId) => `/bizquest/challenges/${challengeId}/join`,
    entries: (challengeId) => `/bizquest/challenges/${challengeId}/entries`,
  }),
  sponsorImpact: Object.freeze({
    overview: '/sponsors/impact',
    campaigns: '/sponsors/campaigns',
    export: '/sponsors/impact/export',
  }),
  posts: Object.freeze({
    create: '/posts',
    draftMe: '/posts/draft/me',
    byId: (postId) => `/posts/${postId}`,
    react: (postId) => `/posts/${postId}/reactions`,
    comments: (postId) => `/posts/${postId}/comments`,
    shares: (postId) => `/posts/${postId}/shares`,
  }),
})
